<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net80</TargetFramework>
    <AssemblyVersion>2026.06.02.7</AssemblyVersion>
    <FileVersion>2026.06.02.7</FileVersion>
    <NoWarn>SA1633</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Providers\Javtrailers\**" />
    <EmbeddedResource Remove="Providers\Javtrailers\**" />
    <None Remove="Providers\Javtrailers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Jellyfin.Controller" Version="10.10.7" />
    <PackageReference Include="Jellyfin.Model" Version="10.10.7" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Api\R18Client.cs~RF1204cac1.TMP" />
    <None Remove="config_page.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="config_page.html" />
  </ItemGroup>

</Project>
